.TH "GOTTET" "6" "February 2014"

.SH "NAME"
gottet \- tetris clone

.SH "SYNOPSIS"
.PP
.B cutemaze

.SH "DESCRIPTION"
.PP
Gottet is a clone of Tetris I wrote for my wife. Pieces fall from the top
of the play area and you can move them horizontally as well as rotate them
before they reach the bottom of the play area. The goal is to create full
lines of pieces, which are then removed. The game is over when the stack
of pieces reaches the top of the play area.

.SH "COPYRIGHT"
.PP
Copyright \(co 2014 Graeme Gott
.PP
This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 3 of the License, or
(at your option) any later version.
.PP
This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.
.PP
You should have received a copy of the GNU General Public License
along with this program. If not, see <http://www.gnu.org/licenses/>.

.SH "AUTHOR"
.PP
Graeme Gott <graeme@gottcode.org>.
