.TH GOTTET 6 "April 2021" "Gottet 1.1.9" "Games Manual"

.SH "NAME"
gottet \- simple falling blocks game

.SH "SYNOPSIS"
.B gottet
[options]

.SH "DESCRIPTION"
Gottet is a clone of Tetris I wrote for my wife. Pieces fall from the top
of the play area and you can move them horizontally as well as rotate them
before they reach the bottom of the play area. The goal is to create full
lines of pieces, which are then removed. The game is over when the stack
of pieces reaches the top of the play area.

.SH "OPTIONS"
.TP
.BR \-h ", " \-\-help
Displays help on commandline options.
.TP
.B \-\-help-all
Displays help including Qt specific options.
.TP
.BR \-v ", " \-\-version
Displays version information.

.SH "SEE ALSO"
.BR qt5options (7)

.SH "REPORTING BUGS"
Report bugs to <gottet@bugs.gottcode.org>.

.SH "COPYRIGHT"
Copyright \(co 2008-2021 Graeme Gott
.PP
Free use of this software is granted under the terms of the GNU General
Public License version 3 (GPLv3). There is NO WARRANTY, to the extent
permitted by law.

.SH "AUTHOR"
Graeme Gott <graeme@gottcode.org>.
